namespace Backend.Seeding;

public static class StressGraphSeedIds
{
    public const string Balanced100 = "stress-balanced-100";
    public const string Wide100 = "stress-wide-100";
    public const string SharedDiamond100 = "stress-shared-diamond-100";
    public const string Balanced1K = "stress-balanced-1k";
    public const string Wide1K = "stress-wide-1k";
    public const string Deep1K = "stress-deep-1k";
    public const string SharedDiamond1K = "stress-shared-diamond-1k";
    public const string Balanced10K = "stress-balanced-10k";
    public const string Wide10K = "stress-wide-10k";
    public const string Deep10K = "stress-deep-10k";
    public const string SharedDiamond10K = "stress-shared-diamond-10k";
    public const string Balanced100K = "stress-balanced-100k";
    public const string Wide100K = "stress-wide-100k";
    public const string Deep100K = "stress-deep-100k";
    public const string SharedDiamond100K = "stress-shared-diamond-100k";
}

public sealed record StressGraphSeedSpec(
    int GraphId,
    string Id,
    string Title,
    string Shape,
    int NodeCount,
    int EdgeCount,
    int MaximumDepth,
    int RootCount,
    int ClaimCount,
    int EvidenceCount,
    int ObjectionCount)
{
    public string Slug => Id;

    public string Description =>
        FormattableString.Invariant(
            $"Deterministic {Shape} stress graph generated by stress-v1 with {NodeCount} nodes.");
}

public static class StressGraphSeedCatalog
{
    public static IReadOnlyList<StressGraphSeedSpec> All { get; } =
    [
        Spec(15, StressGraphSeedIds.Balanced100, "Stress: Balanced Tree (100 Nodes)", "balanced", 100),
        Spec(16, StressGraphSeedIds.Wide100, "Stress: Wide Star (100 Nodes)", "wide", 100),
        Spec(17, StressGraphSeedIds.SharedDiamond100, "Stress: Shared-Diamond DAG (100 Nodes)", "shared-diamond", 100),
        Spec(3, StressGraphSeedIds.Balanced1K, "Stress: Balanced Tree (1,000 Nodes)", "balanced", 1_000),
        Spec(4, StressGraphSeedIds.Wide1K, "Stress: Wide Star (1,000 Nodes)", "wide", 1_000),
        Spec(5, StressGraphSeedIds.Deep1K, "Stress: Deep Chain (1,000 Nodes)", "deep", 1_000),
        Spec(6, StressGraphSeedIds.SharedDiamond1K, "Stress: Shared-Diamond DAG (1,000 Nodes)", "shared-diamond", 1_000),
        Spec(7, StressGraphSeedIds.Balanced10K, "Stress: Balanced Tree (10,000 Nodes)", "balanced", 10_000),
        Spec(8, StressGraphSeedIds.Wide10K, "Stress: Wide Star (10,000 Nodes)", "wide", 10_000),
        Spec(9, StressGraphSeedIds.Deep10K, "Stress: Deep Chain (10,000 Nodes)", "deep", 10_000),
        Spec(10, StressGraphSeedIds.SharedDiamond10K, "Stress: Shared-Diamond DAG (10,000 Nodes)", "shared-diamond", 10_000),
        Spec(11, StressGraphSeedIds.Balanced100K, "Stress: Balanced Tree (100,000 Nodes)", "balanced", 100_000),
        Spec(12, StressGraphSeedIds.Wide100K, "Stress: Wide Star (100,000 Nodes)", "wide", 100_000),
        Spec(13, StressGraphSeedIds.Deep100K, "Stress: Deep Chain (100,000 Nodes)", "deep", 100_000),
        Spec(14, StressGraphSeedIds.SharedDiamond100K, "Stress: Shared-Diamond DAG (100,000 Nodes)", "shared-diamond", 100_000)
    ];

    public static IReadOnlyList<StressGraphSeedSpec> Resolve(
        IEnumerable<string> requestedIds)
    {
        var requested = requestedIds.ToHashSet(StringComparer.Ordinal);
        var knownIds = All.Select(spec => spec.Id).ToHashSet(StringComparer.Ordinal);
        var unknownIds = requested
            .Where(id => string.IsNullOrWhiteSpace(id) || !knownIds.Contains(id))
            .Order(StringComparer.Ordinal)
            .ToList();

        if (unknownIds.Count > 0)
        {
            throw new InvalidStressGraphSeedSelectionException(unknownIds);
        }

        return All.Where(spec => requested.Contains(spec.Id)).ToList();
    }

    private static StressGraphSeedSpec Spec(
        int graphId,
        string id,
        string title,
        string shape,
        int nodeCount)
    {
        var edgeCount = shape == "shared-diamond"
            ? (2 * nodeCount) - 6
            : nodeCount - 1;
        var maximumDepth = shape switch
        {
            "wide" => 1,
            "deep" => nodeCount - 1,
            _ => nodeCount switch
            {
                100 => 4,
                1_000 => 5,
                10_000 => 7,
                100_000 => 9,
                _ => throw new ArgumentOutOfRangeException(
                    nameof(nodeCount),
                    nodeCount,
                    "Unsupported stress graph node count.")
            }
        };

        var evidenceCount = (nodeCount - 1) / 5;
        var objectionCount = nodeCount / 10;
        var claimCount = nodeCount - 1 - evidenceCount - objectionCount;

        return new StressGraphSeedSpec(
            graphId,
            id,
            title,
            shape,
            nodeCount,
            edgeCount,
            maximumDepth,
            1,
            claimCount,
            evidenceCount,
            objectionCount);
    }
}

public sealed class InvalidStressGraphSeedSelectionException : ArgumentException
{
    public InvalidStressGraphSeedSelectionException(IReadOnlyList<string> unknownIds)
        : base($"Unknown stress graph seed ID(s): {string.Join(", ", unknownIds)}.")
    {
        UnknownIds = unknownIds;
    }

    public IReadOnlyList<string> UnknownIds { get; }
}
